name: bloc_library_tutorial
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_bloc: ^0.15.1 # add this

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
